import jsPDF from 'jspdf'
import { formatCurrency } from '@/lib/utils'

const channelLabels = {
  google: 'Google Ads', facebook: 'Facebook', instagram: 'Instagram', linkedin: 'LinkedIn',
  tiktok: 'TikTok', youtube: 'YouTube', twitter: 'X (Twitter)', email: 'Email',
}

const tones = {
  professional: 'Professional', casual: 'Casual & Friendly', humorous: 'Humorous',
  urgent: 'Urgent & Action-Oriented', inspirational: 'Inspirational', educational: 'Educational',
}

const styles = {
  minimal: 'Minimal & Clean', bold: 'Bold & Vibrant', corporate: 'Corporate & Trustworthy',
  playful: 'Playful & Fun', luxury: 'Luxury & Premium', retro: 'Retro & Nostalgic',
}

export const exportToPDF = (brief, output) => {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  let y = 20

  const addText = (text, size, style = 'normal', color = [31, 41, 55]) => {
    if (y > 270) {
      doc.addPage()
      y = 20
    }
    doc.setFontSize(size)
    doc.setFont('helvetica', style)
    doc.setTextColor(...color)
    doc.text(text, margin, y)
    y += size * 0.5 + 4
  }

  const addLine = () => {
    if (y > 275) { doc.addPage(); y = 20 }
    doc.setDrawColor(229, 231, 235)
    doc.line(margin, y, pageWidth - margin, y)
    y += 8
  }

  // Header
  doc.setFillColor(99, 102, 241)
  doc.rect(0, 0, pageWidth, 35, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('Campaign Brief', margin, 18)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text(brief.campaignName || 'Untitled Campaign', margin, 27)
  y = 45

  doc.setTextColor(31, 41, 55)

  // Client Details
  addText('Client Details', 14, 'bold', [79, 70, 229])
  addLine()
  addText(`Client: ${brief.clientName}`, 10)
  addText(`Company: ${brief.companyName}`, 10)
  addText(`Email: ${brief.clientEmail}`, 10)
  addText(`Industry: ${brief.industry}`, 10)
  addText(`Budget: ${formatCurrency(brief.budget)}`, 10)
  addText(`Target Audience:`, 10, 'bold')
  const audienceLines = doc.splitTextToSize(brief.targetAudience, pageWidth - margin * 2 - 5)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  audienceLines.forEach(line => {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.text(line, margin + 5, y)
    y += 6
  })
  y += 4

  // Campaign Objective
  addText('Campaign Objective', 14, 'bold', [79, 70, 229])
  addLine()
  addText(`Objective: ${brief.objective}`, 10)
  addText(`Duration: ${brief.campaignDuration}`, 10)
  addText(`Regions: ${brief.targetRegions?.join(', ').toUpperCase()}`, 10)
  addText('Key Message:', 10, 'bold')
  const msgLines = doc.splitTextToSize(brief.keyMessage, pageWidth - margin * 2 - 5)
  msgLines.forEach(line => {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.text(line, margin + 5, y)
    y += 6
  })
  y += 4

  // Creative
  addText('Creative Preferences', 14, 'bold', [79, 70, 229])
  addLine()
  addText(`Tone: ${tones[brief.tone] || brief.tone}`, 10)
  addText(`Visual Style: ${styles[brief.visualStyle] || brief.visualStyle}`, 10)
  addText(`Channels: ${brief.channels?.map(c => channelLabels[c] || c).join(', ')}`, 10)
  if (brief.brandColors) addText(`Brand Colors: ${brief.brandColors}`, 10)
  y += 4

  // AI Output
  if (output) {
    doc.addPage()
    y = 20

    addText('AI Campaign Output', 14, 'bold', [79, 70, 229])
    addLine()

    addText(`Title: ${output.title}`, 12, 'bold')
    y += 4

    addText('Headlines', 12, 'bold', [79, 70, 229])
    output.headlines?.forEach((h, i) => {
      addText(`${i + 1}. ${h}`, 10)
    })
    y += 4

    addText('Tone Guide', 12, 'bold', [79, 70, 229])
    const toneLines = doc.splitTextToSize(output.toneGuide, pageWidth - margin * 2)
    toneLines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20 }
      doc.text(line, margin, y)
      y += 6
    })
    y += 4

    addText('Channel Budget Allocation', 12, 'bold', [79, 70, 229])
    output.channelBudget?.forEach(ch => {
      addText(`${channelLabels[ch.channel] || ch.channel}: ${ch.percentage}%`, 10)
    })
    y += 4

    addText('Visual Direction', 12, 'bold', [79, 70, 229])
    const visualLines = doc.splitTextToSize(output.visualDirection, pageWidth - margin * 2)
    visualLines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20 }
      doc.text(line, margin, y)
      y += 6
    })
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(156, 163, 175)
    doc.text(
      `Generated by CampaignPro AI  |  Page ${i} of ${pageCount}`,
      pageWidth / 2, 285,
      { align: 'center' }
    )
  }

  doc.save(`campaign-brief-${brief.campaignName || 'draft'}.pdf`)
}
